# Site settings
title: Desarrollo de Software
description: >- # this means to ignore newlines until "baseurl:"
  Conocé más sobre ésta temática
baseurl: ""
url: "https://ddso-utn.github.io"

# Tooltip settings
tooltip-enabled: false
tooltip-label: ""
tooltip-link: ""

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
